#!/usr/bin/perl -w
#Program to calculate GCD naively
#Author Kranthi K. Pamarthi
print "Enter the first number : \n";
chomp ($a = <STDIN>);
print "Enter the second number : \n";
chomp ($b = <STDIN>);
$c = $a;
$d = $b;
$i = 0;
NaiveGCD ();
############################################
######### Function Code ###################
###########################################
sub NaiveGCD
{
while ($a != $b)
{
    print "iteration $i : \n";
if ($a > $b)
{
    $a = $a - $b;
    print "The numbers now are $a and $b\n";
}
else
{
    $b = $b - $a;
    print "The numbers now are $a and $b\n";
}
#print "The final numbers are $a and $b\n";
$i += 1;
}
print "The total number of iterations are $i\n\n";
print "The GCD of $c and $d is $a\n\n";
}

