#!/usr/bin/perl -w
#Program to evaluate polynomials at some value v,-v,iv,-iv using Horner's rule
#Author Kranthi K. Pamarthi

use Math::Complex;
Math::Complex::display_format('cartesian');
print "Enter the array of coefficients from 0 to n: \n";
chomp (@a = <STDIN>);
print "Enter the value to be evaluated : \n";
chomp ($v = <STDIN>);
$vn = 0-$v;
$vc = cplx(0,$v);
$vcn = cplx(0,$vn);
#@p = qw($v $vn);
$n = @a;
$l = $n-1;
horner_eval ();
##################################################
#### New complex Horner Polynomial Evaluation ####
##################################################
sub horner_eval
{
$sum1 = 0;
$sum1c = 0;
$sum2d = 0;
$sum2dc = 0;
$d = $v*$v;
$dc = $vc*$vc;
for ($i = $l;$i >= 0;$i--)
{
if ($i%2==0)
{
 $sum1 = $a[$i] + ($sum1 * $d);
 $sum1c = $a[$i] + ($sum1c * $dc);
}
else
{
    $sum2d = $a[$i] + ($sum2d * $d);
    $sum2dc = $a[$i] + ($sum2dc * $dc);
}
    $sum2 = $sum2d*$v;
    $sum2c = $sum2dc*$vc;
}
#foreach $j (@p)
#{
#if ($j ge 0)
#{
    $sump = $sum1+$sum2;
    print "The value of the polynomial at $v is $sump\n\n";
#}
#else
#{
    $sumn = $sum1-$sum2;
    print "The value of the polynomial at $vn is $sumn\n\n";
    $sumpc = $sum1c+$sum2c;
    print "The value of the polynomial at $vc is $sumpc\n\n";
    $sumnc = $sum1c-$sum2c;
    print "The value of the polynomial at $vcn is $sumnc\n\n";
}

#print "The value of sum upto $i coefficient is $sum\n";

#}
#}
