#!/usr/bin/perl -w
#Program to evaluate polynomials at some real value v,-v using Horner's rule
#Author Kranthi K. Pamarthi
print "Enter the array of coefficients from 0 to n: \n";
chomp (@a = <STDIN>);
print "Enter the value to be evaluated : \n";
chomp ($v = <STDIN>);
$vn = 0-$v;
#@p = qw($v $vn);
$n = @a;
$l = $n-1;
horner_eval ();
##################################################
####### New Horner Polynomial Evaluation #########
##################################################
sub horner_eval
{
$sum1 = 0;
$sum2d = 0;
$d = $v*$v;
for ($i = $l;$i >= 0;$i--)
{
if ($i%2==0)
{
 $sum1 = $a[$i] + ($sum1 * $d);
}
else
{
    $sum2d = $a[$i] + ($sum2d * $d);
}
    $sum2 = $sum2d*$v;
}
#foreach $j (@p)
#{
#if ($j ge 0)
#{
    $sump = $sum1+$sum2;
    print "The value of the polynomial at $v is $sump\n\n";
#}
#else
#{
    $sumn = $sum1-$sum2;
    print "The value of the polynomial at $vn is $sumn\n\n";
}

#print "The value of sum upto $i coefficient is $sum\n";

#}
#}
